# Generated by Django 5.0.1 on 2026-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='polling_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='polling_station_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='dirección mesa'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='table',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mesa'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='notice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='novedad'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='resolución'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='notice_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fecha de novedad'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='polling_station_consulted',
            field=models.BooleanField(default=False, verbose_name='consulta puesto votación'),
        ),
    ]
