# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_add_electoral_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='originprospect',
            name='enable_consult_polling_station',
            field=models.BooleanField(default=False, help_text='Si está activo, se ejecutará una tarea asíncrona cuando se cree un prospecto con este origen', verbose_name='habilitar consulta puesto de votación'),
        ),
    ]
