# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_add_enable_consult_polling_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOptIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(db_index=True, help_text='Identificador único del mensaje de Twilio', max_length=34, unique=True, verbose_name='Message SID')),
                ('account_sid', models.CharField(help_text='Identificador de la cuenta de Twilio', max_length=34, verbose_name='Account SID')),
                ('messaging_service_sid', models.CharField(blank=True, help_text='Identificador del servicio de mensajería', max_length=34, null=True, verbose_name='Messaging Service SID')),
                ('from_number', models.CharField(db_index=True, help_text='Número de WhatsApp del remitente', max_length=20, verbose_name='número remitente')),
                ('to_number', models.CharField(help_text='Número receptor', max_length=20, verbose_name='número receptor')),
                ('body', models.TextField(blank=True, help_text='Contenido del mensaje recibido', verbose_name='contenido del mensaje')),
                ('profile_name', models.CharField(blank=True, help_text='Nombre del perfil de WhatsApp', max_length=255, null=True, verbose_name='nombre del perfil')),
                ('wa_id', models.CharField(blank=True, help_text='Identificador de WhatsApp del contacto', max_length=20, null=True, verbose_name='WhatsApp ID')),
                ('event_type', models.CharField(choices=[('opt-in', 'Opt-in'), ('opt-out', 'Opt-out'), ('message', 'Mensaje'), ('status', 'Estado')], default='message', help_text='Tipo de evento recibido', max_length=20, verbose_name='tipo de evento')),
                ('is_active', models.BooleanField(default=True, help_text='Si el opt-in está activo', verbose_name='activo')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de recepción')),
                ('raw_data', models.JSONField(blank=True, help_text='Datos completos recibidos de Twilio para referencia', null=True, verbose_name='datos completos')),
                ('processed', models.BooleanField(default=False, help_text='Si el opt-in ha sido procesado', verbose_name='procesado')),
                ('prospect', models.ForeignKey(blank=True, help_text='Prospecto relacionado si el número coincide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_opt_ins', to='voters.prospect', verbose_name='prospecto')),
            ],
            options={
                'verbose_name': 'WhatsApp Opt-in',
                'verbose_name_plural': 'WhatsApp Opt-ins',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappoptin',
            index=models.Index(fields=['message_sid'], name='voters_what_message_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoptin',
            index=models.Index(fields=['from_number'], name='voters_what_from_num_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoptin',
            index=models.Index(fields=['received_at'], name='voters_what_receive_idx'),
        ),
    ]
