# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_whatsappoptin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappoptin',
            name='from_number',
            field=models.CharField(
                db_index=True,
                help_text='Número de WhatsApp del remitente (ej. whatsapp:+573001234567)',
                max_length=64,
                verbose_name='número remitente',
            ),
        ),
        migrations.AlterField(
            model_name='whatsappoptin',
            name='to_number',
            field=models.CharField(
                help_text='Número receptor (ej. whatsapp:+573001234567)',
                max_length=64,
                verbose_name='número receptor',
            ),
        ),
        migrations.AlterField(
            model_name='whatsappoptin',
            name='wa_id',
            field=models.CharField(
                blank=True,
                help_text='Identificador de WhatsApp del contacto',
                max_length=64,
                null=True,
                verbose_name='WhatsApp ID',
            ),
        ),
    ]
