# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0007_whatsappoptin_wider_phone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='accepted_terms',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='Aceptación de términos desde formulario embebido',
                verbose_name='aceptación de términos',
            ),
        ),
        migrations.AddField(
            model_name='prospect',
            name='authorize_info_sending',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='Autorización de envío de información desde formulario embebido',
                verbose_name='autorización envío de información',
            ),
        ),
    ]
