# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0008_prospect_accepted_terms_authorize_info_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='allow_whatsapp',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='Indica que se recibió al menos un mensaje de WhatsApp asociado a este prospecto.',
                verbose_name='permite WhatsApp',
            ),
        ),
    ]
