# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0009_prospect_allow_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappoptin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='whatsappoptin',
            name='processed',
        ),
    ]
