# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0010_whatsappoptin_remove_is_active_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='allow_whatsapp',
        ),
    ]
