# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0011_remove_allow_whatsapp_from_prospect'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Número de teléfono normalizado (solo dígitos, sin prefijos)', max_length=20, unique=True, verbose_name='número de teléfono')),
                ('optin_whatsapp', models.BooleanField(default=False, help_text='Si el usuario aceptó opt-in', verbose_name='opt-in WhatsApp')),
                ('optout_whatsapp', models.BooleanField(default=False, help_text='Si el usuario rechazó opt-in', verbose_name='opt-out WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cuenta WhatsApp',
                'verbose_name_plural': 'Cuentas WhatsApp',
                'ordering': ['-updated_at'],
            },
        ),
    ]
