# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0012_whatsappaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppOptIn',
            new_name='WhatsAppMessage',
        ),
    ]
