# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0013_rename_whatsappoptin_to_whatsappmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='prospect',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='phone_number_normalized',
            field=models.CharField(db_index=True, default='', help_text='Número de teléfono normalizado (sin whatsapp:, sin prefijo país)', max_length=20, verbose_name='número de teléfono normalizado'),
            preserve_default=False,
        ),
    ]
