# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0014_whatsappmessage_remove_prospect_add_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='prospect',
            field=models.ForeignKey(
                blank=True,
                help_text='Prospecto relacionado si el número de teléfono coincide',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='whatsapp_accounts',
                to='voters.prospect',
                verbose_name='prospecto'
            ),
        ),
    ]
