# Generated by Django 5.0.1

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    """
    Migra los datos de first_name y last_name a full_name.
    """
    Prospect = apps.get_model('voters', 'Prospect')
    for prospect in Prospect.objects.all():
        first = (prospect.first_name or '').strip()
        last = (prospect.last_name or '').strip()
        if first and last:
            prospect.full_name = f"{first} {last}"
        elif first:
            prospect.full_name = first
        elif last:
            prospect.full_name = last
        else:
            prospect.full_name = ""
        prospect.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0015_whatsappaccount_add_prospect'),
    ]

    operations = [
        # Paso 1: Agregar campo full_name como nullable temporalmente
        migrations.AddField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(
                max_length=200,
                null=True,
                blank=True,
                verbose_name='nombre completo'
            ),
        ),
        # Paso 2: Migrar los datos
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
        # Paso 3: Hacer full_name no nullable
        migrations.AlterField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(
                max_length=200,
                verbose_name='nombre completo'
            ),
        ),
        # Paso 4: Eliminar campos antiguos
        migrations.RemoveField(
            model_name='prospect',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='last_name',
        ),
    ]
