# Generated by Django 5.0.1

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0016_unify_name_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='identification_number',
            field=models.CharField(
                verbose_name=_('número de identificación'),
                max_length=20,
                unique=True,
                db_index=True,
                null=True,
                blank=True,
                help_text=_('Número de identificación único del prospecto (opcional)')
            ),
        ),
    ]
