# Generated by Django migration for chat feature

from django.db import migrations, models
import django.db.models.deletion


def backfill_whatsapp_account_and_direction(apps, schema_editor):
    """Asocia whatsapp_account a mensajes existentes y establece direction='inbound'."""
    WhatsAppMessage = apps.get_model('voters', 'WhatsAppMessage')
    WhatsAppAccount = apps.get_model('voters', 'WhatsAppAccount')
    
    for msg in WhatsAppMessage.objects.all():
        if msg.phone_number_normalized:
            try:
                account = WhatsAppAccount.objects.filter(
                    phone_number=msg.phone_number_normalized
                ).first()
                if account:
                    msg.whatsapp_account = account
            except Exception:
                pass
        msg.direction = 'inbound'
        msg.save(update_fields=['whatsapp_account', 'direction'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0017_make_identification_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(
                choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')],
                db_index=True,
                default='inbound',
                help_text='Entrante (del contacto) o saliente (enviado por nosotros)',
                max_length=10,
                verbose_name='dirección'
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='whatsapp_account',
            field=models.ForeignKey(
                blank=True,
                help_text='Cuenta asociada para agrupación de conversaciones',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='messages',
                to='voters.whatsappaccount',
                verbose_name='cuenta WhatsApp'
            ),
        ),
        migrations.RunPython(backfill_whatsapp_account_and_direction, noop),
    ]
