# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0019_add_chat_sms_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='canal')),
                ('content', models.TextField(help_text='Texto del mensaje enviado', verbose_name='contenido')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to='voters.prospect', verbose_name='prospecto')),
            ],
            options={
                'verbose_name': 'comunicación enviada',
                'verbose_name_plural': 'comunicaciones enviadas',
                'ordering': ['-sent_at'],
            },
        ),
    ]
