# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0020_add_prospect_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectcommunication',
            name='provider_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Identificador del proveedor usado (ej. twilio, onurix)',
                max_length=50,
                verbose_name='proveedor',
            ),
        ),
    ]
