# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0021_prospectcommunication_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='enlace',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='enlace'),
        ),
    ]
