# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voters', '0022_add_prospect_sexo_enlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_uploads/%Y/%m/%d/', verbose_name='archivo')),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('processing', 'procesando'), ('completed', 'completado'), ('failed', 'fallido')], db_index=True, default='pending', max_length=20, verbose_name='estado')),
                ('result_json', models.JSONField(blank=True, help_text='total, created, updated, errors', null=True, verbose_name='resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_jobs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'job de carga masiva',
                'verbose_name_plural': 'jobs de carga masiva',
                'ordering': ['-created_at'],
            },
        ),
    ]
